FROM n8nio/n8n:latest

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV NODE_ENV=production
ENV WEBHOOK_URL=https://RENDER_EXTERNAL_HOSTNAME
ENV N8N_EDITOR_BASE_URL=https://RENDER_EXTERNAL_HOSTNAME
ENV N8N_SECURE_COOKIE=false

EXPOSE 5678